# -*- coding: utf-8 -*-
"""Proyecto Verónica.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lFLrcjyYtBEW5fv-HFFtelqxv9k86Xbg
"""

from random import*

puntajes={} # Diccionario que contiene las puntuaciones.
otrapartida=True # Verfica si se desea jugar otra ronda.
# Ciclo que permite repetir varias rondas
while otrapartida:
  fila=[".",".",".",".",".",".","."] #Filas del tablero.
  ListaPrincipal=[fila.copy(),fila.copy(),fila.copy(),fila.copy(),fila.copy(),fila.copy()] #Tablero completo
  estadojuego=True #Se vuelve false cuando alguien completa 4.
  jugador="" # Marca el participante que está eligiendo movimiento.
  eleccion="" # Alamcena la columna que elige el jugador.
  Nombre_1=Nombre_2=Ficha_jug1=Ficha_jug2="" # Inicializa otras variables necesarias para el programa.
  ganador = "" # Alamcena el ganador de cada ronda.

  #Función que imprime el tablero.
  def imprimir():
    delimiter = "" # Separación de cada elemnto de la fila
    print("+-------+") # Bordes de la tabla
    for i in reversed(ListaPrincipal): # Necesario imprimir la tabla de atras para adelante.
      print("|"+delimiter.join(i)+"|") # Imprimir cada fila con su respectiva separación
    print("+-------+") # Bordes de la tabla

  #Función ingresar valor.
  def colocarficha(ficha,columna):
    global estadojuego,ganador
    # Busca la posición sin ocupar que se encuentre mas abajo de cada columna.
    for k in range(len(ListaPrincipal)):
      if ListaPrincipal[k][columna]==".":
        ListaPrincipal[k][columna]=ficha
        encontrar4(k,columna,ficha) # Revisa si se ganó el juego.
        break
      elif k==5: # Revisa si se colocó un valor en una columna llena y pregunta si desea continuar o dar por terminado el juego.
        print("Esta columna ya está llena, perdiste tu turno, suerte a la proxima...")
        aux=input("Ingresa 0 si ya todas las columnas se encuentran llenas o cualquier otra tecla para reintentarlo: ")
        if aux == "0":
          estadojuego=False
          ganador="ninguno de los dos jugadores."
          break


  #Funcion elegir columna.
  def columna(nombre):
    eleccion = input(nombre+", indica un número de columna del 1 al 7 o pulsa [S] para tentar a la suerte:")
    while eleccion != "S" and eleccion not in ("1","2","3","4","5","6","7"):
      eleccion = input("Valor incorrecto. "+nombre+", indica un número de columna del 1 al 7 o pulsa [S] para tentar a la suerte:")
    if eleccion == "S":
      eleccion = int(choice((1,2,3,4,5,6,7)))
      print(f"Mmm… suerte con eso, se eligió aleatoriamente la columna {eleccion} para tu ficha")
      return eleccion
    else:
      return(int(eleccion))

  #Diagonal 1
  def diagonal1(fila, columna, ficha):
    global estadojuego
    cont=0
    # Llevar a la esquina:
    while fila !=0 and columna !=0:
      columna=columna-1
      fila=fila-1
    # Revisar diagonal
    while columna!=7 and fila!=6:
      if ListaPrincipal[fila][columna]==ficha:
        cont=cont+1
        if cont==4:
          estadojuego = False
          break
      else:
        cont=0
      columna+=1
      fila+=1

  #Diagonal 2:
  def diagonal2(fila, columna, ficha):
    global estadojuego
    cont=0
    # Llevar a la esquina:
    while fila !=0 and columna !=6:
      columna=columna+1
      fila=fila-1
    # Revisar diagonal
    while columna>=0 and fila!=6:
      if ListaPrincipal[fila][columna]==ficha:
        cont=cont+1
        if cont==4:
          estadojuego = False
          break
      else:
        cont=0
      columna-=1
      fila+=1

  #Funcion encontrar 4 seguidas.
  def encontrar4(fila, columna,ficha):
    global estadojuego
    #Columna
    cont=0
    for i in ListaPrincipal:
      if i[columna] == ficha:
        cont=cont+1
        if cont==4:
          estadojuego = False
          break
      else:
        cont=0
    #Fila
    cont=0
    for i in ListaPrincipal[fila]:
      if i == ficha:
        cont=cont+1
        if cont==4:
          estadojuego = False
          break
      else:
        cont=0
    # Diagonal 1:
    diagonal1(fila,columna,ficha)
    # Diagonal 2:
    diagonal2(fila,columna,ficha)


  # CÓDIGO PRINCIPAL:

  #Asignar nombres y fichas a ambos participantes.
  Nombre_1 = input("Por favor indique el nombre del participante #1: ")
  while Ficha_jug1 != "X" and Ficha_jug1 != "O":
    Ficha_jug1 = str(input(f"{Nombre_1} por favor indique con que fichas desea jugar [X] ó [O] (En mayúscula y solo caracteres válidos)"))

  Nombre_2=Nombre_1
  while Nombre_2==Nombre_1:
    Nombre_2 = input(f"Por favor indique el nombre del participante #2 (Distindo al del participante #1 ({Nombre_1})): ")
  if Ficha_jug1 == "X":
    Ficha_jug2 = "O"
  else:
    Ficha_jug2 = "X"

  print(Nombre_2, "te toca jugar con", Ficha_jug2)

  print("Lanzando una moneda al aire para determinar quien inicia la partida.")
  jugador=choice((Nombre_1, Nombre_2))
  print("La partida la inicia",jugador)

  while estadojuego:
    if jugador == Nombre_1:
      ganador = Nombre_1
      colocarficha(Ficha_jug1,columna(Nombre_1)-1)
      jugador=Nombre_2
    else:
      ganador = Nombre_2
      colocarficha(Ficha_jug2,columna(Nombre_2)-1)
      jugador=Nombre_1
    imprimir()
  print(f"El juego lo ha ganado {ganador}, se han actualizado los puntajes.")

  if ganador != "ninguno de los dos jugadores.":
    if ganador in puntajes.keys():
      puntajes[ganador]=puntajes[ganador]+100
    else:
      puntajes.setdefault(ganador,100)
  else:
    if Nombre_1 in puntajes.keys():
      puntajes[Nombre_1]=puntajes[Nombre_1]+50
    else:
      puntajes.setdefault(Nombre_1,50)
    if Nombre_2 in puntajes.keys():
      puntajes[Nombre_2]=puntajes[Nombre_2]+50
    else:
      puntajes.setdefault(Nombre_2,50)
  print("***Tabla de puntuaciones***")
  for key in puntajes.keys():
    print(f"{key} ----> {puntajes[key]}")
  if input("Ingrese 0 si desea terminar de jugar o cualquier otra tecla si desea continuar: ")=="0":
    otrapartida=False